version: '2'
services:
  postgres-db:
    image: postgres:15
    container_name: db-postgres
    environment:
      - .env
    volumes:
      - data_pg:/var/lib/postgresql/data
    ports:
      - 5436:5432/tcp
    networks:
      - my-network

  mysql-db:
    image: mysql:8.0
    container_name: db-mysql
    environment:
      - .env
    ports:
      - 3307:3306/tcp
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my-network
volumes:
  mysql_data: # docker volume create mysql_data
    external: true
  data_pg: # docker volume create postgres_data
    external: true

networks:
  my-network:
    external: true
